api:
  name: "tcc"
  environment: "local"
  telemetry:
    nr:
      name: "tcc"
      license: "888952fca408d30cd24f6bf497100dd760c1NRAL"
database:
    ppt:
      dsn: "root:tcc-pw@tcp(127.0.0.1:3306)/ppt?charset=utf8mb4&parseTime=True&loc=Local"
    nested:
      dsn: "root:tcc-pw@tcp(127.0.0.1:3306)/nested?charset=utf8mb4&parseTime=True&loc=Local"